### DISCUSSION TITLE
Rigidbody bounciness

### DISCUSSION THREAD

**Discussion by Ruttie2006** [avianphysics/avian#513] [Q&A]
I was curious about this crate, so I wrote some code to see how well it works:
```rs
use bevy::{math::{vec2, DVec2}, prelude::*};
use avian2d::prelude::*;

fn main() -> AppExit {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugins(PhysicsPlugins::new(FixedUpdate))
            .insert_resource(Gravity(DVec2::NEG_Y * 100.0))
        .add_systems(Startup, spawn_main)
        .run()
}

fn spawn_main(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());

    commands.spawn((SpriteBundle {
        sprite: Sprite {
            color: Color::srgb(1.0, 0.0, 0.0),
            custom_size: Some(vec2(5.0, 5.0)),
            ..Default::default()
        },
        transform: Transform::from_xyz(0.0, 0.0, 0.0),
        ..Default::default()
    }, RigidBody::Dynamic, Collider::rectangle(5.0, 5.0), Restitution::PERFECTLY_ELASTIC, LockedAxes::ROTATION_LOCKED));

    commands.spawn((SpriteBundle {
        sprite: Sprite {
            color: Color::srgb(1.0, 0.0, 0.0),
            custom_size: Some(vec2(500.0, 5.0)),
            ..Default::default()
        },
        transform: Transform::from_xyz(0.0, -100.0, 0.0),
        ..Default::default()
    }, RigidBody::Static, Collider::rectangle(500.0, 5.0), Restitution::PERFECTLY_ELASTIC));
}
```
When I run this code, it seems to work, however the height the bouncing cube reaches slowly decreases, and after a while it simply no longer bounces.
I would expect that `Restitution::PERFECTLY_ELASTIC` would mean there is no loss in height, and that the cube will bounce forever, am I doing something wrong?

Crate(s) and features:
```toml
avian2d = { version = "0.1.2", default-features = false, features = ["2d", "bevy_scene", "debug-plugin", "default-collider", "f64", "parry-f64", "parallel", "simd"] }
bevy = { version = "0.14.2", features = ["flac", "wayland"] }
log = { version = "0.4.22", features = ["max_level_info", "release_max_level_warn"] }
```
